baseURL = 'https://gennaropecorone-ai.github.io/miosito-hugo/'
languageCode = 'it-it'
title = 'Il mio Blog'
theme = 'hugo-coder'
publishDir = 'docs'

[params]
    author = "Garibaldi"
    description = "GG"
    info = "Sito creato con Hugo"
    avatarurl = "images/Hugo.jpg"