baseURL = 'https://gennaropecorone-ai.github.io/miosito-hugo/'
languageCode = 'it-it'
title = 'G&G CYBER-LAB'
theme = 'hugo-coder'
publishDir = 'docs'

[params]
    author = "G&G"
    # Questa è la scritta che apparirà sotto l'immagine grande
    description = "SISTEMA OPERATIVO G&G - ACCESSO AUTORIZZATO"
    info = "Analisi Dati | Cybersecurity | AI Research"
    avatarurl = "images/GG.jpg"
    
    # --- STYLE HACKER ---
    colorScheme = "dark"
    avatarSize = "350px" # Immagine enorme al centro
    layout = "circle" 

    # Colori Verde Neon su Nero
    [params.colors]
        primary = "#00FF00"
        background = "#000000"
        text = "#00FF00"

# --- NAVBAR (I tasti in alto) ---
[[menu.main]]
    name = "[ HOME ]"
    weight = 1
    url = "/"
[[menu.main]]
    name = "[ DATABASE ]"
    weight = 2
    url = "posts/"
[[menu.main]]
    name = "[ CHI SIAMO ]"
    weight = 3
    url = "about/"